// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $products from "./routes/products.tsx";
import * as $reports from "./routes/reports.tsx";
import * as $AuthGuard from "./islands/AuthGuard.tsx";
import * as $Loading from "./islands/Loading.tsx";
import * as $PageRenderer from "./islands/PageRenderer.tsx";
import * as $PrintButton from "./islands/PrintButton.tsx";
import * as $ProductFilter from "./islands/ProductFilter.tsx";
import * as $Router from "./islands/Router.tsx";
import * as $pages_AdvancedQueries from "./islands/pages/AdvancedQueries.tsx";
import * as $pages_CategoriesList from "./islands/pages/CategoriesList.tsx";
import * as $pages_CustomerCardsList from "./islands/pages/CustomerCardsList.tsx";
import * as $pages_EmployeesList from "./islands/pages/EmployeesList.tsx";
import * as $pages_NewSale from "./islands/pages/NewSale.tsx";
import * as $pages_ProductForm from "./islands/pages/ProductForm.tsx";
import * as $pages_ProductManager from "./islands/pages/ProductManager.tsx";
import * as $pages_ProductSalesReport from "./islands/pages/ProductSalesReport.tsx";
import * as $pages_ReceiptsList from "./islands/pages/ReceiptsList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/products.tsx": $products,
    "./routes/reports.tsx": $reports,
  },
  islands: {
    "./islands/AuthGuard.tsx": $AuthGuard,
    "./islands/Loading.tsx": $Loading,
    "./islands/PageRenderer.tsx": $PageRenderer,
    "./islands/PrintButton.tsx": $PrintButton,
    "./islands/ProductFilter.tsx": $ProductFilter,
    "./islands/Router.tsx": $Router,
    "./islands/pages/AdvancedQueries.tsx": $pages_AdvancedQueries,
    "./islands/pages/CategoriesList.tsx": $pages_CategoriesList,
    "./islands/pages/CustomerCardsList.tsx": $pages_CustomerCardsList,
    "./islands/pages/EmployeesList.tsx": $pages_EmployeesList,
    "./islands/pages/NewSale.tsx": $pages_NewSale,
    "./islands/pages/ProductForm.tsx": $pages_ProductForm,
    "./islands/pages/ProductManager.tsx": $pages_ProductManager,
    "./islands/pages/ProductSalesReport.tsx": $pages_ProductSalesReport,
    "./islands/pages/ReceiptsList.tsx": $pages_ReceiptsList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
